function f() {
  return "exception!";
}
throw f();
