function f() {
  throw "exception!";
}
f();
